AtaRK.WebAPI/Course.MvcApp/Controllers/DeviceController.cs
using Course.MvcApp.ApiServices;
using Course.MvcApp.Models.MvcModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Course.MvcApp.MvcControllers
{
    public class DeviceController : Controller
    {
        private readonly IDeviceApiService _deviceApiService;

        public DeviceController(IDeviceApiService deviceApiService)
        {
            _deviceApiService = deviceApiService ?? throw new ArgumentNullException(nameof(deviceApiService));
        }

        [HttpGet]
        [Route("Show")]
        public async Task<IActionResult> Show([FromQuery] string deviceId)
        {
            var requestResult = await this._deviceApiService.GetDeviceInformation(deviceId);

            return View(requestResult);
        }

        [HttpGet]
        [Route("Update")]
        public async Task<IActionResult> Update(
            [FromQuery] string deviceId,
            [FromQuery] string setting = null,
            [FromQuery] string value = null)
        {
            var deviceUpdateModel = new DeviceUpdateSettingModel()
            {
                DeviceId = deviceId,
                Setting = setting,
                Value = value,
                IsReadonly = !string.IsNullOrEmpty(setting)
            };

            return View(deviceUpdateModel);
        }

        [HttpPost]
        [Route("Update")]
        public async Task<IActionResult> Update([FromForm] DeviceUpdateSettingModel deviceUpdateModel)
        {
            var result = await this._deviceApiService.UpdateDeviceSettings(deviceUpdateModel);

            if (!result)
            {
                return View(deviceUpdateModel);
            }

            return RedirectToAction("Show", new { deviceId = deviceUpdateModel.DeviceId });
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

AtaRK.WebAPI/Course.MvcApp/Controllers/OrganizationController.cs
using Course.MvcApp.ApiServices;
using Course.MvcApp.Models.MvcModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Course.MvcApp.MvcControllers
{
    public class OrganizationController : Controller
    {
        private readonly IOrganizationApiService _organizationApiService;

        public OrganizationController(
            IOrganizationApiService organizationApiService)
        {
            this._organizationApiService = organizationApiService;
        }

        [HttpGet]
        [Route("List")]
        public async Task<IActionResult> List()
        {
            var organizationsResult = await this._organizationApiService.GetCurrentUserOrganizations();

            return this.View(organizationsResult);
        }

        [HttpGet]
        [Route("Invites")]
        public async Task<IActionResult> Invites()
        {
            var operationResult = await this._organizationApiService.GetCurrentUserInvitations();

            return View(operationResult);
        }

        [HttpGet]
        [Route("Invite")]
        public IActionResult Invite([FromQuery] string groupId)
        {
            var createGroupModel = new CreateInviteModel()
            {
                GroupId = groupId,
                Email = string.Empty
            };

            return View(createGroupModel);
        }

        [HttpPost]
        [Route("Invite")]
        public async Task<IActionResult> Invite([FromForm] CreateInviteModel createInviteModel)
        {
            var result = await this._organizationApiService.InviteUser(createInviteModel.GroupId, createInviteModel.Email);

            if (!result)
            {
                return View(createInviteModel);
            }

            return RedirectToAction("View", new { organizationId = createInviteModel.GroupId });
        }

        [HttpGet]
        [Route("OperateInvite")]
        public async Task<IActionResult> OperateInvite(
            [FromQuery] bool doAccept,
            [FromQuery] string inviteId)
        {
            var operationResult = await this._organizationApiService.OperateInvite(inviteId, doAccept);

            return this.RedirectToAction("Invites");
        }

        [HttpGet]
        [Route("View")]
        public async Task<IActionResult> View([FromQuery] string organizationId)
        {
            var organizationInfo = await this._organizationApiService.GetOrganizationInfo(organizationId);

            return View(organizationInfo);
        }

        [HttpGet]
        [Route("Create")]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [Route("Create")]
        public async Task<IActionResult> Create([FromForm] OrganizationModel organizationModel)
        {
            var result = await this._organizationApiService.CreateNewOrganization(organizationModel);

            if (!result)
            {
                this.ModelState.AddModelError(
                    "Invalid operation",
                    "Organization with the same name already exists");

                return this.View(organizationModel);
            }

            return this.RedirectToAction("List");
        }
    }
}

AtaRK.WebAPI/Course.MvcApp/Views/Organization/Create.cshtml
@model Course.MvcApp.Models.MvcModels.OrganizationModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Give your organization a name. Should be unique.</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AtaRK.WebAPI/Course.MvcApp/Views/Organization/Invite.cshtml
@model Course.MvcApp.Models.MvcModels.CreateInviteModel

@{
    ViewData["Title"] = "Invite";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Invite</h1>

<h4>Please, enter email address of whom you would like to invite.</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Invite">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="GroupId" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Invite user" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AtaRK.WebAPI/Course.MvcApp/Views/Organization/Invites.cshtml
@model IEnumerable<Course.MvcApp.Models.MvcModels.InviteModel>

@{
    ViewData["Title"] = "Invites";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Invites</h1>

<h4>There are all invitations users have sent you.</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GroupName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GroupName)
            </td>
            <td>
                @Html.ActionLink("Accept", "OperateInvite", new { doAccept=true, inviteId = item.InviteId }) |
                @Html.ActionLink("Deny", "OperateInvite", new { doAccept=false, inviteId = item.InviteId })
            </td>
        </tr>
}
    </tbody>
</table>

AtaRK.WebAPI/Course.MvcApp/Views/Organization/List.cshtml
@model IEnumerable<Course.MvcApp.Models.MvcModels.OrganizationModel>

@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Your organizations</h1>

<p>
    <a asp-action="Create">Create new organization</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="View" asp-controller="Organization" asp-route-organizationId="@item.OrganizationId">View</a>
            </td>
        </tr>
}
    </tbody>
</table>

AtaRK.WebAPI/Course.MvcApp/Views/Organization/View.cshtml
@model Course.MvcApp.Models.MvcModels.OrganizationShowModel

@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="w-auto mx-auto shadow p-3 mb-5 bg-white rounded">
    <div class="row">
        <div class="col-8">
            <div class="row d-flex justify-content-between">
                <div class="col-9 text-center">
                    <h2>
                        @Model.Name
                    </h2>
                </div>
                <div class="col-3">
                    @if (Model.IsAdmin)
                    {
                        <a class="btn btn-danger" asp-controller="Course" asp-action="Edit" asp-route-courseId="@Model.OrganizationId">
                            Change name
                        </a>
                    }
                </div>
            </div>
            <div class="row my-1">
                <h4>
                    Your role: @Model.UserRole
                </h4>
            </div>
            <div class="text-center my-1">
                <h3>
                    Devices in organization
                </h3>
            </div>
            <table class="table mt-1">
                <thead class="thead-dark">
                <th>
                    Device title
                </th>
                <th>
                </th>
                <th>
                </th>
                </thead>
                @foreach (var device in Model.Devices)
                {
                    <tr>
                        <td>
                            @device.Name
                        </td>
                        <td>
                            <a class="btn btn-info" asp-controller="Device" asp-action="Show" asp-route-deviceId="@device.Id">
                                Go to
                            </a>
                        </td>
                        <td>
                            <a class="btn btn-danger" asp-controller="Device" asp-action="Delete"
                                asp-route-materialId="@device.Id">
                                Delete
                            </a>
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="col-4">
            <div class="text-center">
                <img src="https://st2.depositphotos.com/3489481/5208/i/600/depositphotos_52086275-stock-photo-book-of-life.jpg"
                     width="250" height="250" class="rounded" />
            </div>
            @if (Model.IsAdmin)
            {
                <div class="text-center mt-1">
                    <a class="btn btn-danger" asp-controller="Organization" asp-action="Invite" asp-route-groupId="@Model.OrganizationId">
                        Invite user
                    </a>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}